# Based on
# - https://github.com/marketplace/actions/setup-go-environment

name: go-test-linux.yaml

on: [push]

env:
  LD_LIBRARY_PATH: /opt/senzing/g2/lib
  SENZING_ACCEPT_EULA: I_ACCEPT_THE_SENZING_EULA
  SENZING_TOOLS_DATABASE_URL: "sqlite3://na:na@/tmp/sqlite/G2C.db"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      LD_LIBRARY_PATH: /opt/senzing/g2/lib/
      CGO_ENABLED: 1
    strategy:
      matrix:
        go: ["1.20"]
    name: Go ${{ matrix.go }} - linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - run: wget -qO /tmp/senzingstagingrepo_1.0.1-1_amd64.deb https://senzing-staging-apt.s3.amazonaws.com/senzingstagingrepo_1.0.1-1_amd64.deb
      - run: sudo apt-get -y install /tmp/senzingstagingrepo_1.0.1-1_amd64.deb
      - run: sudo apt-get update
      - run: sudo --preserve-env apt-get -y install senzingapi
      - run: sudo mv /opt/senzing/data/4.0.0/* /opt/senzing/data/
      - run: sudo mkdir /etc/opt/senzing
      - run: sudo cp /opt/senzing/g2/resources/templates/cfgVariant.json     /etc/opt/senzing
      - run: sudo cp /opt/senzing/g2/resources/templates/customGn.txt        /etc/opt/senzing
      - run: sudo cp /opt/senzing/g2/resources/templates/customOn.txt        /etc/opt/senzing
      - run: sudo cp /opt/senzing/g2/resources/templates/customSn.txt        /etc/opt/senzing
      - run: sudo cp /opt/senzing/g2/resources/templates/defaultGNRCP.config /etc/opt/senzing
      - run: sudo cp /opt/senzing/g2/resources/templates/stb.config          /etc/opt/senzing
      - run: sudo cp testdata/senzing-license/g2.lic                         /etc/opt/senzing
      - run: mkdir /tmp/sqlite
      - run: cp testdata/sqlite/G2C.db /tmp/sqlite/G2C.db
      - run: go test -v -p 1 ./...
      - run: pwd
      - run: cp /opt/senzing/g2/sdk/c/*.h ./g2config/
      - run: cp /opt/senzing/g2/sdk/c/*.h ./g2configmgr/
      - run: cp /opt/senzing/g2/sdk/c/*.h ./g2diagnostic/
      - run: cp /opt/senzing/g2/sdk/c/*.h ./g2engine/
      - run: cp /opt/senzing/g2/sdk/c/*.h ./g2product/
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude=G103 -verbose text ./...
