# Based on
# - https://github.com/securego/gosec

name: gosec.yaml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  LD_LIBRARY_PATH: /opt/senzing/g2/lib

jobs:
  gosec:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Install Senzing API
        uses: Senzing/github-action-install-senzing-api@latest
        with:
          senzingapi-version: staging
      - run: |
          mkdir ./g2config/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./g2config/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./g2config/gohelpers
          mkdir ./g2configmgr/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./g2configmgr/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./g2configmgr/gohelpers
          mkdir ./g2diagnostic/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./g2diagnostic/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./g2diagnostic/gohelpers
          mkdir ./g2engine/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./g2engine/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./g2engine/gohelpers
          mkdir ./g2product/gohelpers
          cp /opt/senzing/g2/sdk/c/*.h ./g2product/
          cp /opt/senzing/g2/sdk/c/gohelpers/*.h ./g2product/gohelpers
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: -exclude=G103 -verbose text ./...
